directors:
  input_file: "input"
  output_file: "output" 

export_aula2:
  ext: "csv"
  name: "data_class_2"

export_aula3:
  ext: "yaml"
  name: "data_class_3"  

columns_aula2:
  author:
    - author
  title:
    - title 
  keywords:
    - keywords
  abstract:
    - abstract
  year:
    - year
  type_publication: 
    - type_publication
    - ENTRYTYPE
  doi:
    - doi

columns_aula3:
  title:
    - title   
  jcr_value:
    - jcr_value
    - SJR
  scimago_value:
    - scimago_value
    - Journal Impact Factor

column_title:
  jcs: Full Journal Title
  scm: Title    

find:
  title: BIG
  keywords: DATA
  abstract: BIG DATA
  year: 2020
  type_publication: 
  doi: doi.org
  jcr_value: 
  scimago_value: 

show_excel: true  

   