directors:
  input_file: "input"
  output_file: "output" 

export_aula2:
  ext: "csv"
  name: "data_class_2"

columns_aula2:
  author:
    - author
  title:
    - title 
  keywords:
    - keywords
  abstract:
    - abstract
  year:
    - year
  type_publication: 
    - type_publication
    - ENTRYTYPE
  doi:
    - doi

columns_aula3:
  title:
    - title
    - Full Journal Title
    - Title
  jcr_value:
    - jcr_value
    - SJR
  scimago_value:
    - scimago_value
    - Journal Impact Factor

find:
  title: BIG
  keywords: Big 
  abstract: The
  year:
  type_publication:
  doi:
  jcr_value:
  scimago_value:
   